export const logoClass = `
      flex 
      mx-auto
      font-black 
      text-4xl 
      relative 
      place-items-center 
      before:absolute 
      before:h-[300px] 
      before:w-[480px] 
      before:-translate-x-1/2 
      before:rounded-full 
      before:from-white 
      before:to-transparen
      before:opacity-10
      before:bg-green-900/20 
      before:dark:bg-green-400/10
      before:blur-2xl 
      before:content-[''] 
      after:absolute 
      after:-z-20 
      after:h-[180px] 
      after:w-[240px] 
      after:translate-x-1/3 
      after:bg-gradient-conic 
      after:from-sky-200 
      after:via-blue-200 
      after:blur-2xl 
      after:content-[''] 
      before:dark:bg-gradient-to-br 
      before:dark:from-transparent 
      before:dark:to-green-700 
      before:dark:opacity-10 
      after:dark:from-lime-900/10 
      after:dark:bg-green-900/10
      after:bg-green-300/20
      after:opacity-40 
      before:lg:h-[360px] 
      z-[-1]` as const;
