import "@/app/globals.css";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { StraightLine } from "@/components/StraightLine";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/toaster";
import { cn } from "@/lib/utils";
import Navbar from "../components/navigation/Navbar";
const font = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Juha Mikael ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark" style={{ colorScheme: "dark" }}>
      <body className={cn(" min-h-screen", font.className)}>
        <ThemeProvider attribute="class">
          <Navbar />
          <StraightLine className="border-card-foreground/10" />
          <div className="mx-10 md:mx-20 2xl:mx-96">{children}</div>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
